### ISSUE TITLE
Incorrect aesthetic, technical score order in evaluate_one_video.py

### ISSUE THREAD

**Issue by dknyxh** [VQAssessment/DOVER#16]
On this line https://github.com/VQAssessment/DOVER/blob/69d7b281b1c78fa14e7279fae8c8dab141f9b0e1/evaluate_one_video.py#L135-L137
The order of the dict key is using the order from the yaml file, so it is "technical" first, "aesthetic" second. The subsequent calculation on this line 
https://github.com/VQAssessment/DOVER/blob/69d7b281b1c78fa14e7279fae8c8dab141f9b0e1/evaluate_one_video.py#L19-L20 is thus incorrect because it  assumes the first one is aesthetic, second one is technical. 

In the other file for evaluating a set of videos, it is using the correct order: https://github.com/VQAssessment/DOVER/blob/69d7b281b1c78fa14e7279fae8c8dab141f9b0e1/evaluate_a_set_of_videos.py#L102

**Comment by teowu** [comment]
The 0.6104 is the weight for technical actually, because technical shares more weight in the final VQA result.
You may actually see that the results[1] weight is 0.3896 respectively.

Actually, I notice that the `evaluate_a_set_of_videos.py` is the one with incorrect outputs. I have fixed that.

Thank you for noticing this mistake.

**Comment by Erin-July** [comment]
Hello! I notice that if the `evaluate_a_set_of_videos.py` is the one with incorrect outputs, then is the content of the `dover_predictions/kinetics_400_1.csv` file also wrong? Because the results I ran using the demo video are different from those in `kinetics_400_1.csv`. Also, using the modified code, the aesthetic score is very close to 100, and the technical score is close to 0 (the maximum in the demo folder is 15).
Thank you!

**Comment by jingwu2121** [comment]
Hi, I am having the same issue. Did you manage to solve this? The results generated by `evaluate_a_set_of_videos.py` doesn't match the results in `dover_predictions/kinetics_400_1.csv`. And `spatial_temporal_view_decomposition` isn't done in `evaluate_a_set_of_videos.py`, may I know why is that happening? 

Thank you for your help!
